dist:     trusty
sudo:     required

language: cpp

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

install: 
  - sudo apt-get install -y valgrind 

compiler:
  - g++
  - clang++ 

env:
  - BUILD_TYPE=Debug STANDARD=98 COVERAGE=ON
  - BUILD_TYPE=Release STANDARD=98 COVERAGE=OFF
  - BUILD_TYPE=Debug STANDARD=11 COVERAGE=ON
  - BUILD_TYPE=Release STANDARD=11 COVERAGE=OFF
  - BUILD_TYPE=Debug STANDARD=14 COVERAGE=OFF
  - BUILD_TYPE=Release STANDARD=14 COVERAGE=OFF
  - BUILD_TYPE=Debug STANDARD=17 COVERAGE=OFF
  - BUILD_TYPE=Release STANDARD=17 COVERAGE=OFF

matrix:
  exclude:
  - compiler: g++
    env: BUILD_TYPE=Debug STANDARD=14
  - compiler: g++
    env: BUILD_TYPE=Release STANDARD=14
  - compiler: g++
    env: BUILD_TYPE=Debug STANDARD=17
  - compiler: g++
    env: BUILD_TYPE=Release STANDARD=17
  
script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNING=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$STANDARD -DBUILD_COVERAGE=$COVERAGE
    - cmake --build .
    - ctest --output-on-failure

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
